### ISSUE TITLE
Invalid Library

### ISSUE THREAD

**Issue by schneekluth** [Brunez3BD/ESP32_FlowerCare#3]
How do you install this library? I've cloned this repo into /Arduino/Libraries and also tried to import it as zip but IDE complains about invalid library. Can you add info to README?

**Comment by TheBrunez** [comment]
Hi, I changed some files to solve this issue. Now try to download as a zip and install as usual, it should be fine. Be sure to download and install the BLEDevice library for ESP32, I've also changed the README so you can follow it.
Let me know if this has solved your issue ;)

**Comment by schneekluth** [comment]
Works perfectly! Thanks.
